# docker build -t siegrainwong/aspnetcore-build:2.2-bionic -f Dockerfile-bionic

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-bionic

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -qq update

# Install make to make sure node-sass rebuild
RUN apt-get install make

# Install https://github.com/grpc/grpc dependencies
RUN apt-get install libc6-i386

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

RUN npm --version
RUN node --version

WORKDIR /