FROM mcr.microsoft.com/dotnet/core/sdk:2.2-bionic

# For base builds
# ENV CONFIG_FLAGS="--fully-static --without-npm" DEL_PKGS="libstdc++" RM_DIRS=/usr/include

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -qq update

# Install https://github.com/grpc/grpc dependencies
RUN apt-get install libc6-i386

RUN apt-get install -y nodejs npm
# TODO could uninstall some build dependencies

# fucking debian installs `node` as `nodejs`
RUN update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10

WORKDIR /